package io.bayonet.model.lending;

import io.bayonet.model.base.Actions;
import io.bayonet.model.base.Address;
import io.bayonet.model.base.AuthModel;

/**
 * Created by imranarshad on 11/28/17
 */

public class LendingFeedbackHistoricalRequest {

    /** Auth info of the client */

    private AuthModel auth;


    /** Consumer email */

    private String email;


    /** Consumer name as received by a client */

    private String consumer_name;


    /** Consumer ID used to identify this user in the client's system */

    private String consumer_internal_id;


    /** Consumer phone number - fixed (landline) */

    private String telephone_fixed;


    /** Consumer phone number - mobile */

    private String telephone_mobile;


    /** Consumer reference telephone 1 */

    private String telephone_reference_1;


    /** Consumer reference telephone 2 */

    private String telephone_reference_2;


    /** Consumer reference telephone 3 */

    private String telephone_reference_3;


    /** Consumer RFC */

    private String rfc;


    /** Consumer CURP */

    private String curp;


    /** Consumer address */

    private Address address;


    /** Device fingerprint token generated by Bayonet's device fingerprinting API */

    private String bayonet_fingerprint_token;


    /** Type of transaction - P2P lending, crowdfunding, etc. */

    private String transaction_category;


    /** Internal id of a transaction generated by the client (and not by Bayonet) */

    private String transaction_id;


    /** Unix timestamp when the transaction occurred */

    private Long transaction_time;


    /** Actions to take on the user in question */

    private Actions actions;


    /**
     * Setters
     */
    public void setApiKey(String api_key) {
        this.auth = new AuthModel(api_key);
    }

    public LendingFeedbackHistoricalRequest setEmail(String email) {
        this.email = email;
        return this;
    }

    public LendingFeedbackHistoricalRequest setConsumerName(String consumer_name) {
        this.consumer_name = consumer_name;
        return this;
    }

    public LendingFeedbackHistoricalRequest setConsumerInternalId(String consumer_internal_id) {
        this.consumer_internal_id = consumer_internal_id;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTelephoneFixed(String telephone_fixed) {
        this.telephone_fixed = telephone_fixed;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTelephoneMobile(String telephone_mobile) {
        this.telephone_mobile = telephone_mobile;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTelephoneReference1(String telephone_reference_1) {
        this.telephone_reference_1 = telephone_reference_1;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTelephoneReference2(String telephone_reference_2) {
        this.telephone_reference_2 = telephone_reference_2;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTelephoneReference3(String telephone_reference_3) {
        this.telephone_reference_3 = telephone_reference_3;
        return this;
    }

    public LendingFeedbackHistoricalRequest setRfc(String rfc) {
        this.rfc = rfc;
        return this;
    }

    public LendingFeedbackHistoricalRequest setCurp(String curp) {
        this.curp = curp;
        return this;
    }

    public LendingFeedbackHistoricalRequest setAddress(Address address) {
        this.address = address;
        return this;
    }

    public LendingFeedbackHistoricalRequest setBayonetFingerprintToken(String bayonet_fingerprint_token) {
        this.bayonet_fingerprint_token = bayonet_fingerprint_token;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTransactionCategory(String transaction_category) {
        this.transaction_category = transaction_category;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTransactionId(String transaction_id) {
        this.transaction_id = transaction_id;
        return this;
    }

    public LendingFeedbackHistoricalRequest setTransactionTime(Long transaction_time) {
        this.transaction_time = transaction_time;
        return this;
    }

    public LendingFeedbackHistoricalRequest setActions(Actions actions) {
        this.actions = actions;
        return this;
    }
}
